# Generated by Django 4.1.3 on 2022-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beauty_service', '0003_employee_avatar_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало приема')),
                ('end_time', models.TimeField(verbose_name='Конец приема')),
            ],
        ),
    ]
