# Generated by Django 4.1.3 on 2022-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beauty_service', '0006_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='789123456789', max_length=15, verbose_name='Телефонный номер'),
        ),
    ]
