# Generated by Django 4.1.4 on 2022-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Beauty_service", "0007_alter_client_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="avatar",
            field=models.ImageField(
                blank=True, default="x.svg", null=True, upload_to=""
            ),
        ),
    ]
